#!/bin/sh
die() {
	echo "$1" >&2
	[ -z "$TMP_FILE" ] || rm -f "$TMP_FILE"
	[ -z "$TMP_FILE2" ] || rm -f "$TMP_FILE2"
	exit 1
}

strip_dni(){
	echo "$1" |sed "s%[a-zA-Z]%%g"
}

echo "WARNING!!!: This script adds to ldap server all users tagged as 'new' ('alta = 1') in mySQL itaca.alumnos table"
echo "¿Do you want to proceed? (Write 'YES' in uppercase to continue)"
read a
[ "$a" = "YES" ] || die "Aborted due to user input"


[ $(id -u) -eq 0 ] || die "You must be root to run this script"
 
TMP_FILE="$(tempfile)"
TMP_FILE2="$(tempfile)"
TMP_FILE3="$(tempfile)"

echo "Enter mySQL root password:"
mysql -u root -p -N -B -e "use itaca; select nombre, apellido1, apellido2, gacadcod, NIA, DNI_NORM from alumnos where alta='1';" > "$TMP_FILE"

[ -s "$TMP_FILE" ] || die "Error generating file from mysql"

cat "$TMP_FILE" |while read l; do
	L0="$(echo "$l"|tr "\t" ",")"
	nombre="${L0%%,*}"
	L="${L0#*,}"
	ape1="${L%%,*}"
        L="${L#*,}"
	ape2="${L%%,*}"
        L="${L#*,}"
	grupo="${L%%,*}"
        L="${L#*,}"
	nia="${L%%,*}"
        L="${L#*,}"
	dni="${L%%,*}"
	if [ -z "$dni" ] || [ "$dni" = "NUL" ]; then
		echo "Error, invalid DNI: $L0"
	else
		login="a${dni}"
		if [ -z "$nia" ] || [ "$nia" = "NUL" ]; then
			initpass="${nia}"
			employee="6${initpass}000"
		else
			initpass="$(strip_dni "${dni}")"
			employee="9${initpass}000"
		fi
		gecos="$ape1 $ape2  $nombre"
		echo "Adding user: $gecos"
#		smbldap-useradd -a -g ALUMNOS -d "/datos/usuarios/alumnos/$login" -D "S:" -G "Domain Users" -o "ou=usuarios,dc=centro,dc=com" -c "$gecos"  || true
		rc=0
		echo "$initpass" |smbldap-useradd -a -g ALUMNOS -d "/datos/usuarios/alumnos/${login}" -D "S:" -G "Domain Users" -c "$gecos" -Z employeeNumber=$employee -P  -p "${login}" || rc=$?
		if [ $rc -eq 0 ] ; then
			echo ${login} >> "$TMP_FILE2"
		fi
#FUTURO: create homedir: se puede usar -m (requiere haber montado desde satanas)

	fi
done
# generar fichero con id 

SED_RULE="/^$/d;/^dn:/s%^.*$%\n<alumno%;"

ATTRIB_LIST="uid uidNumber employeeNumber sambaSID gidNumber sambaPrimaryGroupSID gecos"
FIELD_LIST=""
for f in $ATTRIB_LIST ; do
	case "$f" in
		uid)
			F="login"
			;;
		gecos)
			F="nombre_comp"
			;;
		*)
			F="$f"
			;;
	esac
	SED_RULE="${SED_RULE}/^$f:/{s%^$f: % $F=\"%;s%\$%\"%};"
	FIELD_LIST="$FIELD_LIST $F"

done

SED_RULE="${SED_RULE}/^[[:blank:]]*login=/{p;s%login%DNI_NORM%;s%=\".%=\"%}"

ldapsearch -LLL -x -b "dc=centro,dc=com" -D "uid=joindomain,ou=usuarios,dc=centro,dc=com" -W -f "$TMP_FILE2" '(&(objectClass=posixAccount)(uid=%s))' $ATTRIB_LIST | sed -e "$SED_RULE" |sed '1d;/^$/s%^%/>%;$a/>' > "$TMP_FILE3"

# import to mysql ...
IMPORT_SQL="use itaca; delete from ldap_temp; load xml local infile '$TMP_FILE3' into table ldap_temp rows identified by '<alumno>';"

UPDATE_SQL="update alumnos, ldap_temp set"
for f in $FIELD_LIST ; do
	UPDATE_SQL="$UPDATE_SQL alumnos.$f=ldap_temp.$f,"
done
UPDATE_SQL="alumnos.alta='0' where alumnos.DNI_NORM=ldap_temp.DNI_NORM;"
echo "Enter mySQL root password:"
mysql --local-infile=1 -u root -p -N -B -e "$IMPORT_SQL $UPDATE_SQL"

rm -f "$TMP_FILE"
rm -f "$TMP_FILE2"
rm -f "$TMP_FILE3"

