#!/bin/sh
die() {
	echo "$1" >&2
	exit 1
}

usage(){
	die "Usage: $0 <FIELD_NAME>"
}

get_from_db(){
	DB_FIELD="$1"
	mysql -N -B -e "use itaca; select $DB_FIELD from profesores where 1"
}

# main
# ----
[ $(id -u) -eq 0 ] || die "You must be root to run this script"

# check configuration files
for f in /etc/smbldap-tools/smbldap_bind.conf  /etc/smbldap-tools/smbldap.conf; do
	[ -r "$f" ] || die "Missing configuration file $f"
	. $f
done
[ -r /root/.my.cnf ] || die "Missing mysql configurarion in /root/.my.cnf"
export HOME=/root

# test data
fname="$1"
[ "$fname" ] || usage

get_from_db "$fname"
return 0
